#cloud-config

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmY0/Jg/IEw3Ex6j+lX1TfKLcwrNTTQqDoVo57Vo6hKqX6fslKnXOIYrWNyL9LzIZOCtyseC9UMasMSfSMEfWna9mSM38zFXQJAJMH0cvZHKmQtKgg4m8fkCYULCH7dijeuPcU4FYAJpWfj9dEmDfC7TiqH0Li3IzwiKXErpTaYL3XAQnG+pYEHyPfW6Ym+DKLdCsmVSRqKVaLchJ+MS++8O6vQVFiWGtj9Ih7vW8croH397vpADT4Yyjn00TixpKSPilJe690BchGvbHC3oULf6iF6GBGvBurhTCQb3Fm0QgjNwGqgdWhAUEBVPNFm1/+FefjYcaAT/g6cvrYumHn ekraw@umich.edu

package_update: true
package_upgrade: true
packages:
  - git
  - libprotobuf-dev
  - protobuf-compiler

runcmd:
  - cd /home/ubuntu
  - git clone https://github.com/erickrawczyk/neural-style-droplet.git
  - cd /home/ubuntu/neural-style-droplet
  - sudo -u ubuntu -g ubuntu bash init.sh

output : { all : '| tee -a /var/log/cloud-init-output.log' }
